jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      #GHC 8.0:
      #  ARGS: "--resolver lts-9"
      #GHC 8.2:
      #  ARGS: "--resolver lts-11"
      #GHC 8.4:
      #  ARGS: "--resolver lts-12"
      GHC 8.6:
        ARGS: "--resolver lts-14"
      #GHC 8.8:
      #  ARGS: "--resolver lts-15"
      GHC 8.8:
        ARGS: "--resolver lts-16"
      GHC 8.10:
        ARGS: "--resolver lts-17"
      nightly:
        ARGS: "--resolver nightly"
  steps:
  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      curl -sSkL https://get.haskellstack.org/stable/windows-x86_64.zip -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      stack $ARGS test --bench --no-run-benchmarks
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Build and test'
